### ISSUE TITLE
Alias pkgtrends.com domain

### ISSUE THREAD

**Issue by dcramer** [chieftools/pkgtrends#5]
I can transfer ownership or we can simply setup DNS

**Comment by stayallive** [comment]
Both is fine. 

Nameservers are: `ns1.alboweb.nl`, `ns2.alboweb.nl` & `ns3.alboweb.nl`.

Or these DNS entries are also enough:
@ A `185.208.208.157`
@ AAAA `2a0b:3c40:1:220:185:208:208:157`
www CNAME `pkgtrends.com`
